# Copyright (c) 2018-2023, Firas Khalil Khana
# Distributed under the terms of the ISC License

import os
import strutils

import ../../src/constants
import ../../src/pkg_config

radula_behave_pkg_config_environment()

echo "PKG_CONFIG_LIBDIR               :: ", getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_LIBDIR)
echo "PKG_CONFIG_PATH                 :: ", getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_PATH)
echo "PKG_CONFIG_SYSROOT_DIR          :: ", getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_SYSROOT_DIR)
echo "PKG_CONFIG_SYSTEM_INCLUDE_PATH  :: ", getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_SYSTEM_INCLUDE_PATH)
echo "PKG_CONFIG_SYSTEM_LIBRARY_PATH  :: ", getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_SYSTEM_LIBRARY_PATH)

assert getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_LIBDIR).endsWith(RADULA_PATH_PKG_CONFIG_LIBDIR_PATH)
assert getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_PATH).endsWith(RADULA_PATH_PKG_CONFIG_LIBDIR_PATH)
assert getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_SYSROOT_DIR).endsWith(RADULA_PATH_PKG_CONFIG_SYSROOT_DIR)
assert getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_SYSTEM_INCLUDE_PATH).endsWith(RADULA_PATH_PKG_CONFIG_SYSTEM_INCLUDE_PATH)
assert getEnv(RADULA_ENVIRONMENT_PKG_CONFIG_SYSTEM_LIBRARY_PATH).endsWith(RADULA_PATH_PKG_CONFIG_SYSTEM_LIBRARY_PATH)
