[package]
name = "radula"
version = "1.1.0"
authors = ["Firas Khalil Khana <firasuke@glaucuslinux.org>"]
edition = "2021"
description = "glaucus's radula"
readme = "README.md"
repository = "https://github.com/glaucuslinux/radula"
license = "ISC"
keywords = ["glaucus", "radula"]

[dependencies]
colored = "2.0.0"
futures-util = "0.3.19"
git2 = "0.13.25"
indicatif = { git = "https://github.com/mitsuhiko/indicatif" }
num_cpus = "1.13.1"
reqwest = { version = "0.11.8", features = ["stream"] }
serde = { version = "1.0.133", features = ["derive"] }
tar = "0.4.38"
tokio = { version = "1.15.0", features = [
    "fs",
    "io-util",
    "macros",
    "process",
    "rt-multi-thread",
] }
toml = "0.5.8"

[profile.release]
opt-level = 3
debug = false
lto = true
incremental = false
codegen-units = 1
