[package]
name = "radula"
version = "1.1.3"
authors = ["Firas Khalil Khana <firasuke@glaucuslinux.org>"]
edition = "2021"
description = "glaucus's radula"
readme = "README.md"
repository = "https://github.com/glaucuslinux/radula"
license = "ISC"
keywords = ["glaucus", "radula"]

[dependencies]
bzip2 = { version = "0.4.3", features = ["tokio"] }
colored = "2.0.0"
flate2 = { version = "1.0.23", default-features = false, features = [
    "zlib-ng-compat",
] }
futures-util = "0.3.21"
git2 = { version = "0.14.3", features = ["zlib-ng-compat"] }
indicatif = { git = "https://github.com/mitsuhiko/indicatif", features = [
    "improved_unicode",
] }
num_cpus = "1.13.1"
reqwest = { version = "0.11.10", features = ["stream"] }
serde = { version = "1.0.137", features = ["derive"] }
tar = "0.4.38"
tokio = { version = "1.18.1", features = [
    "fs",
    "io-util",
    "macros",
    "process",
    "rt-multi-thread",
] }
toml = { version = "0.5.9", features = ["preserve_order"] }
xxhash-rust = { version = "0.8.5", features = ["xxh3"] }
xz2 = { git = "https://github.com/alexcrichton/xz2-rs", features = ["tokio"] }
zstd = { version = "0.11.1", default-features = false, features = ["zstdmt"] }

[profile.release]
opt-level = 3
debug = false
lto = true
incremental = false
codegen-units = 1
