[package]
name = "radula-rs"
version = "0.1.0"
authors = ["Firas Khalil Khana <firasuke@glaucuslinux.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
