# Copyright (c) 2018-2023, Firas Khalil Khana
# Distributed under the terms of the ISC License

import std/os

import constants

#
# Bootstrap Functions
#

proc radula_behave_bootstrap_environment*() =
    let path = parentDir(getCurrentDir())

    putEnv(RADULA_ENVIRONMENT_DIRECTORY_GLAUCUS, path)

    putEnv(RADULA_ENVIRONMENT_DIRECTORY_BACKUPS, path / RADULA_DIRECTORY_BACKUPS)
    putEnv(RADULA_ENVIRONMENT_DIRECTORY_CERATA, path / RADULA_DIRECTORY_CERATA)
    putEnv(RADULA_ENVIRONMENT_DIRECTORY_CROSS, path / RADULA_DIRECTORY_CROSS)
    putEnv(RADULA_ENVIRONMENT_DIRECTORY_LOGS, path / RADULA_DIRECTORY_LOGS)
    putEnv(RADULA_ENVIRONMENT_DIRECTORY_SOURCES, path / RADULA_DIRECTORY_SOURCES)
    putEnv(RADULA_ENVIRONMENT_DIRECTORY_TEMPORARY, path / RADULA_DIRECTORY_TEMPORARY)
    putEnv(RADULA_ENVIRONMENT_DIRECTORY_TOOLCHAIN, path / RADULA_DIRECTORY_TOOLCHAIN)

    putEnv(RADULA_ENVIRONMENT_PATH, getEnv(
        RADULA_ENVIRONMENT_DIRECTORY_TOOLCHAIN) / RADULA_PATH_USR /
        RADULA_PATH_BIN & ':' & getEnv(RADULA_ENVIRONMENT_PATH))

proc radula_behave_bootstrap_initialize*() =
    createDir(getEnv(RADULA_ENVIRONMENT_DIRECTORY_BACKUPS))
    createDir(getEnv(RADULA_ENVIRONMENT_DIRECTORY_LOGS))
    createDir(getEnv(RADULA_ENVIRONMENT_DIRECTORY_SOURCES))
    createDir(getEnv(RADULA_ENVIRONMENT_DIRECTORY_TEMPORARY))
